# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"
pr:
- "*"

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.16.3'

- task: Docker@2
  inputs:
    containerRegistry: 'danielfbm-dockerhub'
    repository: 'danielfbm/plugin-example'
    command: 'buildAndPush'
    Dockerfile: 'controller/Dockerfile'
    buildContext: 'controller'

