# permissions for end users to edit plugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-editor-role
rules:
- apiGroups:
  - plugins.danielfbm.github.com
  resources:
  - plugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugins.danielfbm.github.com
  resources:
  - plugins/status
  verbs:
  - get
