// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bar.proto

/*
Package bar is a generated protocol buffer package.

It is generated from these files:
	bar.proto

It has these top-level messages:
	BarsResponse
	Empty
*/
package bar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BarsResponse struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *BarsResponse) Reset()                    { *m = BarsResponse{} }
func (m *BarsResponse) String() string            { return proto.CompactTextString(m) }
func (*BarsResponse) ProtoMessage()               {}
func (*BarsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BarsResponse) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*BarsResponse)(nil), "bar.BarsResponse")
	proto.RegisterType((*Empty)(nil), "bar.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bar service

type BarClient interface {
	Bars(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BarsResponse, error)
}

type barClient struct {
	cc *grpc.ClientConn
}

func NewBarClient(cc *grpc.ClientConn) BarClient {
	return &barClient{cc}
}

func (c *barClient) Bars(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BarsResponse, error) {
	out := new(BarsResponse)
	err := grpc.Invoke(ctx, "/bar.Bar/Bars", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bar service

type BarServer interface {
	Bars(context.Context, *Empty) (*BarsResponse, error)
}

func RegisterBarServer(s *grpc.Server, srv BarServer) {
	s.RegisterService(&_Bar_serviceDesc, srv)
}

func _Bar_Bars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServer).Bars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bar.Bar/Bars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServer).Bars(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bar.Bar",
	HandlerType: (*BarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bars",
			Handler:    _Bar_Bars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bar.proto",
}

func init() { proto.RegisterFile("bar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4a, 0x2c, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x4a, 0x2c, 0x52, 0x52, 0xe1, 0xe2, 0x71, 0x4a,
	0x2c, 0x2a, 0x0e, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xd8, 0xb9, 0x58,
	0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0x74, 0xb8, 0x98, 0x9d, 0x12, 0x8b, 0x84, 0x54, 0xb9, 0x58,
	0x40, 0xba, 0x84, 0xb8, 0xf4, 0x40, 0xc6, 0x81, 0xa5, 0xa4, 0x04, 0xc1, 0x6c, 0x64, 0xc3, 0x92,
	0xd8, 0xc0, 0x16, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0x89, 0x71, 0x88, 0x75, 0x00,
	0x00, 0x00,
}
